In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.metrics import mean_absolute_percentage_error, \
mean_absolute_error, r2_score, mean_squared_error

In [3]:
import os
os.getcwd()

'G:\\My Drive\\Study\\Time Series Analysis Udemy\\random codes'

In [4]:
os.chdir(r'G:\My Drive\Study\Time Series Analysis Udemy\Data\time series analysis forecasting')
os.getcwd()

'G:\\My Drive\\Study\\Time Series Analysis Udemy\\Data\\time series analysis forecasting'

In [5]:
df = pd.read_csv('SPY.csv', index_col ='Date', parse_dates=True )

In [6]:
df.head()

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2010-01-04,112.370003,113.389999,111.510002,113.330002,92.246048,118944600
2010-01-05,113.260002,113.680000,112.849998,113.629997,92.490204,111579900
2010-01-06,113.519997,113.989998,113.430000,113.709999,92.555328,116074400
2010-01-07,113.500000,114.330002,113.180000,114.190002,92.946060,131091100
2010-01-08,113.889999,114.620003,113.660004,114.570000,93.255348,126402800

In [7]:
df['ClosePrediction'] = df['Close'].shift(1)

In [8]:
df.head()

,Open,High,Low,Close,Adj Close,Volume,ClosePrediction
Date,,,,,,,
2010-01-04,112.370003,113.389999,111.510002,113.330002,92.246048,118944600,NaN
2010-01-05,113.260002,113.680000,112.849998,113.629997,92.490204,111579900,113.330002
2010-01-06,113.519997,113.989998,113.430000,113.709999,92.555328,116074400,113.629997
2010-01-07,113.500000,114.330002,113.180000,114.190002,92.946060,131091100,113.709999
2010-01-08,113.889999,114.620003,113.660004,114.570000,93.255348,126402800,114.190002

In [9]:
y_true = df.iloc[1:]['Close']
y_pred = df.iloc[1:]['ClosePrediction']

## Metrics

In [15]:
# SSE
(y_true - y_pred).dot(y_true - y_pred)

np.float64(6330.374289492605)

In [19]:
# MSE = SSE/n
mean_squared_error(y_true, y_pred)

2.798573956451196

In [20]:
# MSE calculating it manually
(y_true - y_pred).dot(y_true - y_pred) / len(y_true)

np.float64(2.798573956451196)

In [22]:
#RMSE
# mean_squared_error(y_true, y_pred, squared = False) # no longer works in the newer version of sklearn
from sklearn.metrics import root_mean_squared_error
root_mean_squared_error(y_true, y_pred)

1.672893886787562

In [34]:
np.mean(y_true)

np.float64(185.71845265261163)

In [35]:
# looking at the root mean squared error and comparing this with the mean of y_true, it shows that RMSE as a percentage of mean of y_true is very small which is great
# and it is great because it is naive forecast

In [23]:
#RMSE done manually
np.sqrt((y_true - y_pred).dot(y_true - y_pred) / len(y_true))

np.float64(1.672893886787562)

In [25]:
#mean absolute error
mean_absolute_error(y_pred,y_true)

1.1457559803120336

In [27]:
#mean absolute error done manually
np.sum(abs(y_true-y_pred))/len(y_true)

np.float64(1.1457559803120336)

In [30]:
r2_score(y_true, y_pred)
## THIS LOOKS AWESOME SINCE MORE THAN 99% ERRORS EXPLAINABLE

0.9989603259063914

In [31]:
#MAPE
mean_absolute_percentage_error(y_true, y_pred)

0.006494073151422373

In [32]:
np.mean((abs(y_pred-y_true)/abs(y_true)))

np.float64(0.006494073151422373)

In [33]:
#sMAPE
numerator = abs(y_pred-y_true)
denominator = (abs(y_pred) + abs(y_true))/2
np.mean(numerator/denominator)

np.float64(0.006491365814068417)